In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.1.0'

In [3]:
house_prices_data = pd.read_csv('../data/housing.csv')

In [4]:
house_prices_data.shape

(20640, 10)

In [5]:
house_prices_data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [6]:
house_prices_data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [7]:
uniq_val_in_op = house_prices_data.nunique()['ocean_proximity']
print(uniq_val_in_op)

5


In [8]:
house_prices_data[house_prices_data['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [9]:
mean_with_null = house_prices_data['total_bedrooms'].mean()
print(mean_with_null)

537.8705525375618


In [10]:
mean_without_null = house_prices_data['total_bedrooms'].fillna(mean_with_null).mean()
print(mean_without_null)

537.8705525375617


In [11]:
house_prices_data['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [12]:
diminished_df = house_prices_data[house_prices_data['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']]
diminished_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [13]:
X = diminished_df.values
print(X)

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [14]:
X_transpose = X.T
print(X_transpose)

[[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]


In [15]:
XTX = np.dot(X_transpose, X)
print(XTX)

[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [16]:
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [17]:
y = np.array([950, 1300, 800, 1000, 1300])

In [18]:
first_multiplication = np.dot(XTX_inverse, X_transpose)
w = np.dot(first_multiplication, y)
print(w)
print(w[-1])

[23.12330961 -1.48124183  5.69922946]
5.699229455065586
